import org.jetbrains.kotlin.gradle.dsl.ExplicitApiMode

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.binary.compatibility)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.dokka)
}

group = property("GROUP") as String
version = property("VERSION_NAME") as String

// Single source of truth for the version the client tag reports: the build
// generates a constant, so the tag can never rot the way a hand-bumped one
// would (a lesson from the Go SDK shipping sdk-go/dev for five releases).
val generateVersion = tasks.register("generateVersion") {
    val dir = layout.buildDirectory.dir("generated/spooVersion/kotlin")
    val versionValue = version.toString()
    inputs.property("version", versionValue)
    outputs.dir(dir)
    doLast {
        val file = dir.get().file("me/spoo/internal/SpooVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by the build. Do not edit.
            package me.spoo.internal

            internal const val SPOO_SDK_VERSION: String = "$versionValue"
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    explicitApi()
    jvmToolchain(21)

    jvm()
    androidLibrary {
        namespace = "me.spoo"
        compileSdk = 36
        minSdk = 21
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateVersion)
            dependencies {
                api(libs.kotlinx.coroutines.core)
                api(libs.kotlinx.serialization.json)
                api(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.ktor.client.mock)
                implementation(libs.kotlinx.coroutines.test)
            }
        }
        jvmMain {
            dependencies {
                implementation(libs.ktor.client.okhttp)
            }
        }
        androidMain {
            dependencies {
                implementation(libs.ktor.client.okhttp)
            }
        }
    }

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }
}

apiValidation {
    // The android target's ABI is the common surface; the jvm dump covers it.
    ignoredProjects += emptyList<String>()
}

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)
    signAllPublications()
}
