org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official

GROUP=me.spoo
VERSION_NAME=0.1.0

POM_NAME=spoo
POM_DESCRIPTION=Official Kotlin Multiplatform SDK for the spoo.me link management API
POM_URL=https://github.com/spoo-me/spoo-kotlin
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/spoo-me/spoo-kotlin
POM_SCM_CONNECTION=scm:git:git://github.com/spoo-me/spoo-kotlin.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/spoo-me/spoo-kotlin.git
POM_DEVELOPER_ID=spoo-me
POM_DEVELOPER_NAME=spoo.me
POM_DEVELOPER_URL=https://github.com/spoo-me
